### PR TITLE
Replaced use of hard-coded Windows paths in R with file.path

### PR DESCRIPTION
**Pull request by devilgate**
Wherever I found "`\\`" I've applied the R `file.path` function.

The R code was generating various files using hard-coded Windows-style paths, rooted at `C:\rifDemo`. I've replaced all those using `file.path` without specifying a root directory. That causes the files to be generated under `rifDemo` in the directory from which Tomcat was launched.

That's not ideal, as the Tomcat user might not always have write access to that directory, but it's OK for development.

The limited testing I've been able to do won't have exercised all the lines I've changed, though, so hopefully you guys can check all that out.

### CODE REVIEW

**Comment by peterhambly** [comment]
Tried to create:  rifDemo/scratchSpace/d/401/-/500/s/409/datarif40_run_R_env.bat on Windows; caused extract to fail:
```
R temporary directory: c:\rifDemo\scratchSpace\d401-500\s409 was not created by Adj_Cov_Smooth_JRI.R
```
Actually created: ```C:\Program Files\Apache Software Foundation\Tomcat 8.5\bin\rifDemo\scratchSpace\d\401\-\500\s\409```

**Comment by devilgate** [comment]
Hi Peter,

OK, I've fixed the problem with R generating the files in the wrong place, and also fixed the failing test.

For the files: I've changed the way we're using the `extractDirectory` property. The idea now is to set it to be the root directory for `rifDemo`. So on Windows, if you want the `C:\rifDemo\...` structure as previously, you need to set `extractDirectory` to `C:`. I've changed the shipped version to have that value.

I expect that to work fine; I have it set to a specific directory on my Mac and the `rifDemo` directory and all its subdirectories are now created there.

Let me know if you think changing the use of `extractDirectory` is going to cause problems somewhere else. It doesn't seem likely from what I've seen, but obviously you know the system a lot better than I do. If it is going to be a problem I'll introduce a new property for this setting and use that instead.

**Comment by peterhambly** [comment]
Hi Martin,

Excellent. I'll test it in a bit. I am going to add more code to easy
the environment, path and R setup to make setting up the RIF easier.
Regards,

Peter

On Wed, May 9, 2018, at 10:26 AM, Martin McCallion wrote:
> Hi Peter,


> OK, I've fixed the problem with R generating the files in the wrong
> place, and also fixed the failing test.> For the files: I've changed the way we're using the extractDirectory
> property. The idea now is to set it to be the root directory for
> rifDemo. So on Windows, if you want the C:\rifDemo\... structure as
> previously, you need to set extractDirectory to C:. I've changed the
> shipped version to have that value.> I expect that to work fine; I have it set to a specific directory on
> my Mac and the rifDemo directory and all its subdirectories are now
> created there.> Let me know if you think changing the use of extractDirectory is going
> to cause problems somewhere else. It doesn't seem likely from what
> I've seen, but obviously you know the system a lot better than I do.
> If it is going to be a problem I'll introduce a new property for this
> setting and use that instead.> — You are receiving this because your review was requested. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 



Peter.

-------------------------------------------------------------------
Email: phambly@fastmail.co.uk




Links:

  1. https://github.com/smallAreaHealthStatisticsUnit/rapidInquiryFacility/pull/26#issuecomment-387679510

**Comment by devilgate** [comment]
Just realised I had done that change only on the Postgres version. I've just applied it to the MS one as well.

**Comment by peterhambly** [comment]
Tested OK

**Pull request merged**
