### PR TITLE
Change database access in R to use RJDBC

### PR DESCRIPTION
**Pull request by devilgate**
This change switches the R code from using ODBC to using JDBC, via the RJDBC package. This means we don't have to set up both ODBC and JDBC connections, making installation simpler.

Hopefully you guys can check that this works properly in more situations than I've been able to try @peterhambly  @bparkes.

### CODE REVIEW

**Comment by devilgate** [comment]
To start with the last: what's your `extractDirectory` set to? mine is `/Users/martin/Dropbox/work/sahsu/rifdirs/rifDemo`, so it creates `scratchSpace` in that. If yours is set to `C:\rifDemo\scratchSpace`, say, then you'd see the behaviour you describe.

As to the main problem: I tried running the 1002 study. Unfortunately I can't run studies with smoothing on my Mac at present because of the INLA bug I described in #27. I tried it without smoothing, and it worked, but I suppose that doesn't help.

I'm going to fire up the Windows PC and have a look at it there.

Lastly, "Files: s18.zip. No extract CSV!" I'm not sure what that's about. Where should we be expecting to see `s18.zip`?

**Comment by peterhambly** [comment]
```Files: s18.zip. No extract CSV:``` Yes I was expecting one; hence the R error.

Re: extract directory - this is a change from Kev's setup; I will check it when I review again; especially the documentation and the ZIP file creator

**Comment by devilgate** [comment]
Just to be totally clear: are you seeing this when you run a study, or when you do `Export -> Export Study Tables`?

**Comment by peterhambly** [comment]
R was unable to connect to the database (should it be?) as the function did not exist: ```connectToDb() ERROR:  could not find function "connectToDb"```

```

R Error/Warning/Notice: 
Attaching package: 'INLA'

R Error/Warning/Notice: The following object is masked from 'package:pryr':

    f

R Error/Warning/Notice: Checking rgeos availability: FALSE
 	Note: when rgeos is not available, polygon geometry 	computations in maptools depend on gpclib,
 	which has a restricted licence. It is disabled by default;
 	to enable gpclib, type gpclibPermit()
R Error/Warning/Notice: Loading required package: spData
R Error/Warning/Notice: To access larger datasets in this package, install the spDataLarge
package with: `install.packages('spDataLarge',
repos='https://nowosad.github.io/drat/', type='source'))`
In runRSmoothingFunctions in JRI script 
In establishTableNamesCopy:  C:\Program Files\Apache Software Foundation\Tomcat 8.5/webapps/rifServices/WEB-INF/classes/performSmoothingActivity.R  to:  scratchSpace/d1-100/s19/data/performSmoothingActivity.R 
Copy:  C:\Program Files\Apache Software Foundation\Tomcat 8.5/webapps/rifServices/WEB-INF/classes/Adj_Cov_Smooth_csv.R  to:  scratchSpace/d1-100/s19/data/Adj_Cov_Smooth_csv.R 
Copy:  C:\Program Files\Apache Software Foundation\Tomcat 8.5/webapps/rifServices/WEB-INF/classes/rif40_run_R.bat  to:  scratchSpace/d1-100/s19/data/rif40_run_R.bat 
Create:  scratchSpace/d1-100/s19/data/rif40_run_R_env.bat 

11:29:21.480 [http-nio-8080-exec-5] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.RService$LoggingConsole]:
rFlushConsole[4] calls: 3, length: 97, time period: PT49.537S

Table names established
About to test exitValue 1 and connection 
Could not connect to database

11:29:21.490 [http-nio-8080-exec-5] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.generic.util.RIFMemoryManager]:
Thread list, 41 threads >>>
Thread: Thread-5; ID : 55; state: TIMED_WAITING; memory: 24.1 KB
Thread: Log4j2-TF-7-Scheduled-1; ID : 53; state: TIMED_WAITING; memory: 304 B
Thread: Log4j2-TF-7-Scheduled-1; ID : 50; state: TIMED_WAITING; memory: 304 B
Thread: ajp-nio-8009-AsyncTimeout; ID : 46; state: TIMED_WAITING; memory: 5.1 KB
Thread: ajp-nio-8009-Acceptor-0; ID : 45; state: RUNNABLE; memory: 80 B
Thread: ajp-nio-8009-ClientPoller-1; ID : 44; state: RUNNABLE; memory: 8.8 KB
Thread: ajp-nio-8009-ClientPoller-0; ID : 43; state: RUNNABLE; memory: 8.8 KB
Thread: ajp-nio-8009-exec-10; ID : 42; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-9; ID : 41; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-8; ID : 40; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-7; ID : 39; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-6; ID : 38; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-5; ID : 37; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-4; ID : 36; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-3; ID : 35; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-2; ID : 34; state: WAITING; memory: 32 B
Thread: ajp-nio-8009-exec-1; ID : 33; state: WAITING; memory: 32 B
Thread: http-nio-8080-AsyncTimeout; ID : 32; state: TIMED_WAITING; memory: 5.1 KB
Thread: http-nio-8080-Acceptor-0; ID : 31; state: RUNNABLE; memory: 253.3 KB
Thread: http-nio-8080-ClientPoller-1; ID : 30; state: RUNNABLE; memory: 29.3 KB
Thread: http-nio-8080-ClientPoller-0; ID : 29; state: RUNNABLE; memory: 32.6 KB
Thread: http-nio-8080-exec-10; ID : 28; state: WAITING; memory: 18.5 MB
Thread: http-nio-8080-exec-9; ID : 27; state: WAITING; memory: 43.2 MB
Thread: http-nio-8080-exec-8; ID : 26; state: WAITING; memory: 1.5 GB
Thread: http-nio-8080-exec-7; ID : 25; state: WAITING; memory: 19.2 MB
Thread: http-nio-8080-exec-6; ID : 24; state: WAITING; memory: 15.5 MB
CURRENT thread: http-nio-8080-exec-5; ID : 23; state: RUNNABLE; memory: 29.6 GB
Thread: http-nio-8080-exec-4; ID : 22; state: WAITING; memory: 33.0 MB
Thread: http-nio-8080-exec-3; ID : 21; state: WAITING; memory: 19.6 MB
Thread: http-nio-8080-exec-2; ID : 20; state: WAITING; memory: 26.3 MB
Thread: http-nio-8080-exec-1; ID : 19; state: WAITING; memory: 39.2 MB
Thread: ContainerBackgroundProcessor[StandardEngine[Catalina]]; ID : 18; state: TIMED_WAITING; memory: 298.4 KB
Thread: NioBlockingSelector.BlockPoller-2; ID : 15; state: RUNNABLE; memory: 3.5 KB
Thread: NioBlockingSelector.BlockPoller-1; ID : 14; state: RUNNABLE; memory: 17.6 KB
Thread: GC Daemon; ID : 13; state: TIMED_WAITING; memory: 0 B
Thread: Log4j2-TF-7-Scheduled-1; ID : 12; state: TIMED_WAITING; memory: 928 B
Thread: Attach Listener; ID : 5; state: RUNNABLE; memory: 0 B
Thread: Signal Dispatcher; ID : 4; state: RUNNABLE; memory: 0 B
Thread: Finalizer; ID : 3; state: WAITING; memory: 403.4 KB
Thread: Reference Handler; ID : 2; state: WAITING; memory: 0 B
Thread: main; ID : 1; state: RUNNABLE; memory: 61.8 MB
<<<
Total thread memory: 31.4 GB
Memory: max: 9.8 GB, total: 4.0 GB, free: 2.2 GB, available: 5.8 GB; processors: 4
11:29:21.490 [http-nio-8080-exec-5] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.SmoothResultsSubmissionStep]:
Rengine Stopped, exit value==1==
11:29:21.494 [http-nio-8080-exec-5] ERROR org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.SmoothResultsSubmissionStep]:
JRI R script exception
getMessage:          RIFServiceException: R script execution error; trace:
connectToDb() ERROR:  could not find function "connectToDb" ; call stack:  connectToDb 
connectToDb exitValue: 1
.
getRootCauseMessage: RIFServiceException: R script execution error; trace:
connectToDb() ERROR:  could not find function "connectToDb" ; call stack:  connectToDb 
connectToDb exitValue: 1
.
getThrowableCount:   1
getRootCauseStackTrace >>>
1 error(s). Error code is 'R_ERROR'. Message list is: 'R script execution error; trace:
connectToDb() ERROR:  could not find function "connectToDb" ; call stack:  connectToDb 
connectToDb exitValue: 1
```

**Comment by devilgate** [comment]
First of all, yes, R should be trying to connect to the DB. The difference is that now it's using JDBC instead of ODBC. If you remember I tried to change it so that all the DB access would be done from Java, and R would just do the calculations. But it turned out that the changes to the R scripts were going to be too big and complex. It's still something I'd like to do, but not at the moment.

But the message that the `dbConnect` function is not found: that's misleading. Basically if anything goes wrong in that function, you get the message that it's not found. I've just pushed a set of changes that should make it easier to debug. The R code was swallowing most of the output statements, with the idea that it returned them to the Java, which would then write them to the log if there had been a problem. But somewhere in that stack, they were all getting lost.

I've spent most of yesterday and today getting the RIF running on this slow old Windows PC, so I could investigate your problem. It's working now -- but so is test 1002! It runs through fine for me, and I can zip and download the output.

Maybe something I've changed has fixed your problem, but that seems unlikely. But at least we might get some better output if you try it again and it still fails.

**Comment by peterhambly** [comment]
OK, I was confused. .Same error as before: ```connectToDb() ERROR:  could not find function "connectToDb" ; call stack:  connectToDb```. This is defined in **JdbcHandler.R**; which is sourced.

There is also:
```
R Error/Warning/Notice: Loading required package: RJDBC
R Error/Warning/Notice: Error in library(RJDBC) : there is no package called 'RJDBC'
R Error/Warning/Notice: In addition: R Error/Warning/Notice: Warning message:
R Error/Warning/Notice: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :R Error/Warning/Notice: 
 R Error/Warning/Notice:  there is no package called 'RJDBC'
```

So the solution to the first problem is to install **RJDBC** as an administrator.

It then fails fetching data. The query works (see later) so (Postgres only) *PERFORM rif40_sql_pkg.rif40_startup();* has not been run: ```ERROR: unrecognized configuration parameter "rif40.send_debug_to_info"```

```
... JDBC connection established 
Connected to DB
connectToDb exitValue: 0
About to test exitValue 0 and connection 
Performing basic stats and smoothing
About to fetch extract table outside of the try
JDBC EXTRACT TABLE NAME: rif_studies.s22_extract
Querying by JDBC: select * from rif_studies.s22_extract 
JDBC Saving extract frame to: scratchSpace/d1-100/s22/data/tmp_s22_extract.csv

14:25:14.696 [http-nio-8080-exec-10] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.RService$LoggingConsole]:
rFlushConsole[3] calls: 1, length: 52, time period: PT1.099S

JDBC rif_studies.s22_extract numberOfRows=108328==

14:25:16.088 [http-nio-8080-exec-10] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.RService$LoggingConsole]:
rFlushConsole[4] calls: 5, length: 266, time period: PT1.392S

About to fetch extract table
JDBC EXTRACT TABLE NAME: rif_studies.s22_extract
Querying by JDBC: select * from rif_studies.s22_extract 
JDBC Saving extract frame to: scratchSpace/d1-100/s22/data/tmp_s22_extract.csv
JDBC rif_studies.s22_extract numberOfRows=108328==

14:25:16.385 [http-nio-8080-exec-10] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.RService$LoggingConsole]:
rFlushConsole[5] calls: 67, length: 2386, time period: PT50.354S

About to get adjacency matrix
Querying by JDBC: SELECT * FROM rif40_xml_pkg.rif40_GetAdjacencyMatrix( 22 ) 
ERROR IN QUERY! SQL>  SELECT * FROM rif40_xml_pkg.rif40_GetAdjacencyMatrix( 22 ) ; error:  Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", : Unable to retrieve JDBC result set for SELECT * FROM rif40_xml_pkg.rif40_GetAdjacencyMatrix( 22 ) (ERROR: unrecognized configuration parameter "rif40.send_debug_to_info"
  Where: PL/pgSQL function rif40_log_pkg.rif40_log(rif40_log_pkg.rif40_log_debug_level,character varying,character varying[]) line 110 at FETCH
SQL statement "SELECT rif40_log_pkg.rif40_log('DEBUG1', 'rif40_GetAdjacencyMatrix', '[52005] SQL>'||E'\n'||'%;', sql_stmt::VARCHAR)"
PL/pgSQL function rif40_xml_pkg.rif40_getadjacencymatrix(integer) line 271 at PERFORM) 
```

```
sahsuland=> SELECT * FROM rif40_xml_pkg.rif40_GetAdjacencyMatrix( 22 );
     area_id     | num_adjacencies |                                                                                                                                                                                                 adjacency_list                                                                                                                     
-----------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 01.001.000100.1 |              18 | 01.001.000100.2,01.001.000200.1,01.002.000500.1,01.002.000500.4,01.002.000500.7,01.002.000600.1,01.002.000600.6,01.002.000600.8,01.002.000700.2,01.002.000800.7,01.002.000900.1,01.002.000900.2,01.002.000900.4,01.002.001300.1,01.002.001300.5,01.002.001500.2,01.004.011100.1,01.005.002400.1
 01.001.000100.2 |               2 | 01.001.000100.1,01.001.000200.1
 01.001.000200.1 |               4 | 01.001.000100.1,01.001.000100.2,01.001.000300.1,01.005.002400.1
 01.001.000300.1 |               1 | 01.001.000200.1
 01.002.000300.1 |               3 | 01.002.000300.2,01.002.000300.3,01.002.000300.4
 01.002.000300.2 |               4 | 01.002.000300.1,01.002.000300.4,01.002.000500.3,01.002.000600.2
 01.002.000300.3 |               3 | 01.002.000300.1,01.002.000300.4,01.002.000300.5
 01.002.000300.4 |               6 | 01.002.000300.1,01.002.000300.2,01.002.000300.3,01.002.000300.5,01.002.000400.3,01.002.000600.2
 01.002.000300.5 |               3 | 01.002.000300.3,01.002.000300.4,01.002.000400.3
```

SQL Server got a lot further:

```
About to save to tableIn saveDataFrameToDatabaseTableSaving data frame to: scratchSpace/d1-100/s10/data/tmp_s10_map.csv
Creating temporary table: peter.tmp_s10_map
About to write temporary table: peter.tmp_s10_map
Stack tracer >>>

 .handleSimpleError(function (obj) 
{
    calls = sys.calls()
    calls = ca stop("execute JDBC update query failed in dbSendUpdate (", .jcall(x, "S", " .local(conn, statement, ...) dbSendUpdate(conn, inss, list = list) dbSendUpdate(conn, inss, list = list) .local(conn, name, value, ...) dbWriteTable(connection, name = temporarySmoothedResultsTableName, value =  JdbcHandler.R#213: dbWriteTable(connection, name = temporarySmoothedResults Adj_Cov_Smooth_JRI.R#325: withVisible(expr) Adj_Cov_Smooth_JRI.R#325: withCallingHandlers(withVisible(expr), error = er JdbcHandler.R#194: withErrorTracing({
    if (dbExistsTable(connection, tem doTryCatch(return(expr), name, parentenv, handler) tryCatchOne(expr, names, parentenv, handlers[[1]]) tryCatchList(expr, names[-nh], parentenv, handlers[-nh]) doTryCatch(return(expr), name, parentenv, handler) tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names tryCatchList(expr, classes, parentenv, handlers) JdbcHandler.R#193: tryCatch({
    withErrorTracing({
        if (dbExistsTa Adj_Cov_Smooth_JRI.R#427: saveDataFrameToDatabaseTable(result) Adj_Cov_Smooth_JRI.R#375: tryCatch({
    withErrorTracing({
        cat(pas runRSmoothingFunctions() 
<<< End of stack tracer.
saveDataFrameToDatabaseTable() ERROR:  execute JDBC update query failed in dbSendUpdate (The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.) ; call stack:  .local 
saveDataFrameToDatabaseTable() ERROR:  execute JDBC update query failed in dbSendUpdate (The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.) ; call stack:  conn 
saveDataFrameToDatabaseTable() ERROR:  execute JDBC update query failed in dbSendUpdate (The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.) ; call stack:  statement 
saveDataFrameToDatabaseTable() ERROR:  execute JDBC update query failed in dbSendUpdate (The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.) ; call stack:  ... 
saveDataFrameToDatabaseTable finishing
UPDATE rif_studies.s10_map a SET direct_standardisation=b.direct_standardisation,adjusted=b.adjusted,observed=b.observed,expected=b.expected,lower95=b.lower95,upper95=b.upper95,relative_risk=b.relative_risk,smoothed_relative_risk=b.smoothed_relative_risk,posterior_probability=CASE WHEN b.posterior_probability  = 'NAN' THEN NULL ELSE b.posterior_probability END, posterior_probability_upper95=CASE WHEN b.posterior_probability_upper95  = 'NAN' THEN NULL ELSE b.posterior_probability_upper95 END, posterior_probability_lower95=CASE WHEN b.posterior_probability_lower95  = 'NAN' THEN NULL ELSE b.posterior_probability_lower95 END, residual_relative_risk=CASE WHEN b.residual_relative_risk  = 'NAN' THEN NULL ELSE b.residual_relative_risk END, residual_rr_lower95=CASE WHEN b.residual_rr_lower95  = 'NAN' THEN NULL ELSE b.residual_rr_lower95 END, residual_rr_upper95=CASE WHEN b.residual_rr_upper95  = 'NAN' THEN NULL ELSE b.residual_rr_upper95 END, smoothed_smr=CASE WHEN b.smoothed_smr  = 'NAN' THEN NULL ELSE b.smoothed_smr END, smoothed_smr_lower95=CASE WHEN b.smoothed_smr_lower95  = 'NAN' THEN NULL ELSE b.smoothed_smr_lower95 END, smoothed_smr_upper95=CASE WHEN b.smoothed_smr_upper95  = 'NAN' THEN NULL ELSE b.smoothed_smr_upper95 END FROM peter.tmp_s10_map b WHERE a.study_id=b.study_id AND a.band_id=b.band_id AND a.inv_id=b.inv_id AND a.genders=b.genders AND a.area_id=b.area_idR Error/Warning/Notice: Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate (Incorrect syntax near 'a'.)
R Error/Warning/Notice: Error: object 'returnValues' not found
```

Here I suspect the problem is with NAN not being interpreted as NULL, for which there is no code:

```
			# NA values have been appearing in DB columns that should be null.
			# data <- do.call(data.frame, lapply(data, function(x) {
			# 	replace(x, is.na(x), NULL)
			# }
			# ))

			if (db_driver_prefix == "jdbc:sqlserver") {
					data<-do.call(data.frame, lapply(data, function(x) {
						replace(x, is.infinite(x),NA) # Replace INF will NA for SQL Server
					}
					))
			}
```

**Comment by devilgate** [comment]
Installing RJDBC is essential, of course. I thought you had already done that. I've updated some of the docs to mention it, but I'll do a more comprehensive rewrite when we've got all this sorted out. 

As to `unrecognized configuration parameter "rif40.send_debug_to_info"`: I hit that weeks ago,and eventually discovered that you can fix it by adding it to your `postgresql.conf`. I also found another line it needed, resulting in this:

```
rif40.send_debug_to_info = off
rif40.debug = ''
```

Are you saying that running that stored procedure has the same effect? What else does it do, and does it only last for the session? If so I would favour using the configuration option, rather than running something each time we connect.

I wrote some code to work around the NAN/null stuff, but maybe it's incomplete or has got lost. 

**But:** the most important question is, why is this working for me (including on Windows), but not for you?

**Comment by devilgate** [comment]
Following up on that, I've reinstated the commented-out `replace` with `is.na` that you quoted above. I thought I had copied that from the `RIF_odbc.R` version, but apparently not. The odd thing is it breaks the PostgreSQL functionality, so I've put it inside the `if`. Also I don't understand why the `nullProtect` function doesn't prevent the problem on SQL Server.

Anyway, if you set the `postgresql.conf` settings I mentioned yesterday, and use the latest version, it _should_ work on both databases.

**Comment by peterhambly** [comment]
Fromat of the SQL Server UPDATE statement is wrong : ```UPDATE peter.s11_map a``` is not allowed, requires an INNER JOIN with the FROM, should be:

```
UPDATE peter.s11_map 
SET direct_standardisation=b.direct_standardisation,
adjusted=b.adjusted,observed=b.observed,
expected=b.expected,lower95=b.lower95,
upper95=b.upper95,
relative_risk=b.relative_risk,smoothed_relative_risk=b.smoothed_relative_risk,
posterior_probability=CASE WHEN b.posterior_probability  = 'NAN' THEN NULL ELSE b.posterior_probability END, 
posterior_probability_upper95=CASE WHEN b.posterior_probability_upper95  = 'NAN' THEN NULL ELSE b.posterior_probability_upper95 END, 
posterior_probability_lower95=CASE WHEN b.posterior_probability_lower95  = 'NAN' THEN NULL ELSE b.posterior_probability_lower95 END, 
residual_relative_risk=CASE WHEN b.residual_relative_risk  = 'NAN' THEN NULL ELSE b.residual_relative_risk END, 
residual_rr_lower95=CASE WHEN b.residual_rr_lower95  = 'NAN' THEN NULL ELSE b.residual_rr_lower95 END, 
residual_rr_upper95=CASE WHEN b.residual_rr_upper95  = 'NAN' THEN NULL ELSE b.residual_rr_upper95 END, 
smoothed_smr=CASE WHEN b.smoothed_smr  = 'NAN' THEN NULL ELSE b.smoothed_smr END,
smoothed_smr_lower95=CASE WHEN b.smoothed_smr_lower95  = 'NAN' THEN NULL ELSE b.smoothed_smr_lower95 END, 
smoothed_smr_upper95=CASE WHEN b.smoothed_smr_upper95  = 'NAN' THEN NULL ELSE b.smoothed_smr_upper95 END 
FROM peter.s11_map AS a LEFT OUTER JOIN peter.tmp_s11_map b 
ON (a.study_id=b.study_id AND a.band_id=b.band_id AND a.inv_id=b.inv_id AND a.genders=b.genders AND a.area_id=b.area_id);
GO
```
Am fixing

**Comment by devilgate** [comment]
There's nothing like a standard...

**Comment by peterhambly** [comment]
Update. Ugly [SQL Server driver error](https://stackoverflow.com/questions/50340258/sqlclient-error-after-updating-windows-the-incoming-tabular-data-stream-tds)

``
saveDataFrameToDatabaseTable() ERROR:  execute JDBC update query failed in dbSendUpdate (The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.`
``

Am debating what to do.

**Comment by devilgate** [comment]
Oh dear, that does look nasty. Assuming this is in `JDBCHandler.R`, I got a lot of the code from the ODBC version, `RIF_odbc.R`. I tried to simplify the SQL and reduce it to a single version. The older one had separate versions for the two DBs.

Maybe the best solution would be to go back to that approach, much though I dislike it (not least because what happens when we need to support Oracle, or DB2, or MySQL or...?)

**Comment by peterhambly** [comment]
Postgres OK, various fixes. SQL Server error to be tested on non Win 10 systems

* Handlers for NaN, INF, zero length strings
* Fix SQL Server update
* Repaired error handlers (Java side is still broken)
* Fix index naming
* Verified table creation on SQL Server is OK

Will almost certainly need SQL Server to use ODBC code

**Comment by devilgate** [comment]
OK, that sounds like a viable workaround. We'll have to do make some changes so that the correct version gets called in each case. It'll be annoying to have a lot of unnecessary if/else branches messing up the code, but hopefully we can keep them to a minimum.

The best approach might be to have the same function names in the O and J versions of the DB scripts, and only source the applicable one. I don't think that will be quite possible, given the differences between the two libraries, but I'll see what I can do. 

However, all of that might have to wait till after I'm back from holiday. This week is all about getting the risk analysis script to run -- though we're almost there.

**Comment by peterhambly** [comment]
OK, all done. SQL server uses ODBC, Postgres JDBC

**Pull request merged**
