### PR TITLE
Issue 59 cannot view error messages that disappear

### PR DESCRIPTION
**Pull request by peterhambly**
Added messages modal to disease submission #59
messages modal

### CODE REVIEW

**Comment by peterhambly** [comment]
Beware; this is branched from the DM-RA switch fix #52 and does not include the final patch

**Comment by peterhambly** [comment]
It does now!

**Comment by devilgate** [comment]
I still get the "Submission state verification failed with 1 error(s)" message.

screen shot 2018-09-05 at 17 30 16

**Comment by peterhambly** [comment]
Fixed on both branches #52, #59. Made submission state verification errors visible. Also fixed faults where messages were not going through to front end logger.

**Comment by devilgate** [comment]
Looking good in that I can switch between DM and RA and the correct code blocks are executed. My comments regarding the Java code are still outstanding. I can tidy those up if you want.

**Pull request merged**
