### PR TITLE
More steps towards bringing the two database paths together

### PR DESCRIPTION
**Pull request by devilgate**
This branch suppresses all the failing tests that I couldn't easily fix. That at least makes it easier to see when a new change has broken something.

It also abstracts more of the database-specific code into common classes and interfaces.

### CODE REVIEW

**Comment by devilgate** [comment]
Hi Peter, Any chance you can get this reviewed and merged into `master` soon? The longer we wait the harder it will be to keep up with other changes. And I've got another branch based on this that's queued up behind it.

**Comment by peterhambly** [comment]
Hi Martin,

I am still getting a lot of errors from the front end:
```
+4.1: +4.1: [1] ERROR: Unable to assign a read connection.  rifc-util-alert.js:192
+4.1: +4.1: [2] ERROR: Could not retrieve status of studies  rifc-util-alert.js:192
+4.1: [rifc-dsub-status.js] Could not retrieve status of studies: undefined  rifc-util-alert.js:192
+4.1: +4.1: [3] ERROR: Unable to assign a read connection.  rifc-util-alert.js:192
+4.1: +4.1: [4] ERROR: Could not retrieve your project information from the database  rifc-util-alert.js:192
+8: +8: [5] ERROR: Unable to assign a read connection.  rifc-util-alert.js:192
```
[RIF_middleware.2018-04-24-1.log](https://github.com/smallAreaHealthStatisticsUnit/rapidInquiryFacility/files/1943917/RIF_middleware.2018-04-24-1.log)

Regards,

Peter

**Comment by devilgate** [comment]
The latest change should stop the NPEs in  `MSSQLConnectionManager`. That side was holding its own, non-static, copy of the `List`s that cache the `Connection`s.

**Comment by peterhambly** [comment]
SQL Server and Postgres now OK, R causes a Java crash; same in both ports:

```
2018-04-26 13:35:57,853 http-nio-8080-exec-5 DEBUG Now writing to C:\Program Files\Apache Software Foundation\Tomcat 8.5/log4j2/2018
-04/RIF_middleware.2018-04-26-1.log at 2018-04-26T13:35:57.852+0100
Rengine.eval(Rpid<-Sys.getpid()): BEGIN Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(Rpid<-Sys.getpid()): END (OK)Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(Rpid): BEGIN Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(Rpid): END (OK)Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(rm(list=ls())): BEGIN Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(rm(list=ls())): END (OK)Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(print(.libPaths())): BEGIN Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(print(.libPaths())): END (OK)Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(print(sessionInfo())): BEGIN Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(print(sessionInfo())): END (OK)Thread[http-nio-8080-exec-7,5,main]
Rengine.eval(source("C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\rifServices\WEB-INF\classes\Adj_Cov_Smooth_JRI.R
")): BEGIN Thread[http-nio-8080-exec-7,5,main]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff832835266, pid=15488, tid=0x00000000000006d0
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0x55266]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Program Files\Apache Software Foundation\Tomcat 8.5\bin\hs_err_pid15488.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by peterhambly** [comment]
The R issue is now fixed. Windows paths in R need to be escaped! Will continue testing

**Pull request merged**
